spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:domus_dev}
spring.datasource.username=${DB_USERNAME:domus_dev}
spring.datasource.password=${DB_PASSWORD:domus_dev}

security.jwt.secret=${JWT_SECRET:RE9NVVNfREVWX1NFQ1JFVF9GT1JfSldUX1NFUlZJQ0VfQkFTRV9LRVlfMjAyNg==}

management.endpoint.health.show-details=always
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
